<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ti-new-tag-input ti-valid</name>
   <tag></tag>
   <elementGuidId>8f0b9d82-6f7f-4535-abcc-d98142cf7452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ti-new-tag-input.ti-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4b9e15e-6744-40b1-9b9d-049c81a72cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tags</value>
      <webElementGuid>7ed3f8f4-ad20-412e-aa29-9b448c9bf2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3478401-934a-4b50-9bb2-22c8191ce24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>36960a52-487f-45cb-97e9-8234a28273d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tags</value>
      <webElementGuid>4bc1c08c-f614-4b17-a940-ef29ccec57d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ti-new-tag-input ti-valid</value>
      <webElementGuid>66f2d749-de4a-4e4c-9fd0-9bf915bf036b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optional-info&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;vue-tags-input force-background-tags-input&quot;]/div[@class=&quot;ti-input&quot;]/ul[@class=&quot;ti-tags&quot;]/li[@class=&quot;ti-new-tag-input-wrapper&quot;]/input[@class=&quot;ti-new-tag-input ti-valid&quot;]</value>
      <webElementGuid>e2facfb7-812d-4ec3-a6e0-9e858544e59d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>630b82bc-dc98-4853-bf4e-db7ea175e7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='optional-info']/div[3]/div[2]/div/div/div/ul/li/input</value>
      <webElementGuid>374ee06e-bef2-4599-b118-1cfa6748c00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>fc8f5c1b-11b8-4b97-83c8-0f36b496dae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tags' and @type = 'text' and @title = 'Tags']</value>
      <webElementGuid>7be207b0-d1a6-4bd5-b959-d08ea65995f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
