<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Transfers</name>
   <tag></tag>
   <elementGuidId>ab61cba5-99e0-4d12-8dd3-b09e63c3b9e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='transaction-menu']/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.treeview-menu > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>693c1f03-5346-4e5a-8e9b-b393efdfe1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:8080/transactions/transfers</value>
      <webElementGuid>0ee6323c-8a32-4c50-9fde-7940b494d4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    
                    Transfers
                </value>
      <webElementGuid>6837662d-df4e-4bdc-a024-a5859bc9105b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transaction-menu&quot;)/ul[@class=&quot;treeview-menu&quot;]/li[3]/a[1]</value>
      <webElementGuid>10532bde-d4da-41a0-8b51-503dd92ac851</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='transaction-menu']/ul/li[3]/a</value>
      <webElementGuid>e5e9ba56-6561-408d-9134-564af3638c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8080/transactions/transfers']</value>
      <webElementGuid>8975852d-e8d6-44d2-9f1e-a65be5eb5e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[3]/a</value>
      <webElementGuid>9bdc4dc9-ae57-4cb5-b561-b826c6803222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost:8080/transactions/transfers' and (text() = '
                    
                    Transfers
                ' or . = '
                    
                    Transfers
                ')]</value>
      <webElementGuid>71103fa9-040d-409b-a8bc-481cb0fbd4c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
